/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define BINDIR "/usr/bin"

#define DATADIR "/usr/share"

#define GETTEXT_PACKAGE "loongson-info"

#define ICONSDIR "/usr/share/loongson-info/icons/"

#define LIBDIR "/usr/lib64"

#define LIBEXECDIR "/usr/libexec"

#define LOCALSTATEDIR "/var"

#define LUNAR_CALENDAR_LOCALEDIR "/usr/share/locale"

#define PACKAGE_NAME "loongson-info"

#define PACKAGE_VERSION "1.0.0"

#define SYSCONFDIR "/etc"

#define VERSION "1.0.0"

